/*
 * generated by Xtext
 */
package org.xtext.example.mydsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MyDsl01UiModule extends org.xtext.example.mydsl.ui.AbstractMyDsl01UiModule {
	public MyDsl01UiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
