/*
* generated by Xtext
*/
package org.xtext.example.mydsl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class MyDsl01StandaloneSetup extends MyDsl01StandaloneSetupGenerated{

	public static void doSetup() {
		new MyDsl01StandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

