/*
 * generated by Xtext
 */
package org.xtext.example.mydsl.ui.contentassist

import org.xtext.example.mydsl.ui.contentassist.AbstractMyDsl01ProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class MyDsl01ProposalProvider extends AbstractMyDsl01ProposalProvider {
}
