/*
 * generated by Xtext
 */
package de.wwu.pi.mdsd.crudDsl.ui.contentassist

import de.wwu.pi.mdsd.crudDsl.ui.contentassist.AbstractCrudDslProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class CrudDslProposalProvider extends AbstractCrudDslProposalProvider {
}
