/**
 * generated by Xtext
 */
package org.xtext.example.mydsl.validation;

import org.xtext.example.mydsl.validation.AbstractMyDsl01Validator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class MyDsl01Validator extends AbstractMyDsl01Validator {
}
