/*
 * generated by Xtext
 */
package de.wwu.pi.mdsd.crudDsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class CrudDslUiModule extends de.wwu.pi.mdsd.crudDsl.ui.AbstractCrudDslUiModule {
	public CrudDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
