/*
 * generated by Xtext
 */
package de.wwu.pi.mdsd01.crudDsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CrudDslRuntimeModule extends de.wwu.pi.mdsd01.crudDsl.AbstractCrudDslRuntimeModule {

}